//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SWE30010_Group04_WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int SaleItemId { get; set; }
        public int SaleId { get; set; }
        public int StockId { get; set; }
    
        public virtual Sale Sale { get; set; }
        public virtual Stock Stock { get; set; }
    }
}
